-- MySQL Script generated by MySQL Workbench
-- Fri May  4 10:00:14 2018
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema reprografia
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `reprografia` ;

-- -----------------------------------------------------
-- Schema reprografia
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `reprografia` DEFAULT CHARACTER SET utf8 COLLATE utf8_latvian_ci;
USE `reprografia` ;

-- -----------------------------------------------------
-- Table `reprografia`.`perfil`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `reprografia`.`perfil` ;

CREATE TABLE IF NOT EXISTS `reprografia`.`perfil` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `descricao` VARCHAR(255) NOT NULL,
  `nome` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;

CREATE UNIQUE INDEX `tipo_UNIQUE` ON `reprografia`.`perfil` (`nome` ASC);


-- -----------------------------------------------------
-- Table `reprografia`.`pessoa`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `reprografia`.`pessoa` ;

CREATE TABLE IF NOT EXISTS `reprografia`.`pessoa` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(55) NOT NULL,
  `login` VARCHAR(20) NOT NULL,
  `senha` VARCHAR(255) NOT NULL,
  `email` VARCHAR(55) NULL,
  `ativo` TINYINT(1) NULL,
  `tipo_pessoa` VARCHAR(31) NOT NULL,
  `perfil_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  CONSTRAINT `fk_pessoa_perfil`
    FOREIGN KEY (`perfil_id`)
    REFERENCES `reprografia`.`perfil` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE UNIQUE INDEX `login_UNIQUE` ON `reprografia`.`pessoa` (`login` ASC);

CREATE INDEX `fk_pessoa_perfil_idx` ON `reprografia`.`pessoa` (`perfil_id` ASC);


-- -----------------------------------------------------
-- Table `reprografia`.`permissao`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `reprografia`.`permissao` ;

CREATE TABLE permissao(
  id INT NOT NULL AUTO_INCREMENT,
  nome varchar(255) NOT NULL,
  descricao varchar(255),
  papel varchar(255) NOT NULL,
  permissao_pai_id INT,
  PRIMARY KEY (id),
  CONSTRAINT permissao_pai_fkey FOREIGN KEY (permissao_pai_id) REFERENCES permissao (id)
) ENGINE = InnoDB;

-- -----------------------------------------------------
-- Table `reprografia`.`perfil_permissao`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `reprografia`.`perfil_permissao` ;

CREATE TABLE perfil_permissao(
  perfil_id INT NOT NULL,
  permissoes_id INT NOT NULL,
  CONSTRAINT perfilpermissao_perm_fkey FOREIGN KEY (permissoes_id) REFERENCES permissao (id),
  CONSTRAINT perfilpermissao_perfil_fkey FOREIGN KEY (perfil_id) REFERENCES perfil (id)
) ENGINE = InnoDB;

-- -----------------------------------------------------
-- Table `reprografia`.`segurancaapi`
-- -----------------------------------------------------

DROP TABLE IF EXISTS `reprografia`.`segurancaapi` ;

CREATE TABLE segurancaapi (
    id INT NOT NULL AUTO_INCREMENT,
    token varchar(1000) NOT NULL,
    expiracao_token timestamp,
    pessoa_id  INT NOT NULL,
    CONSTRAINT segurancaapi_pkey PRIMARY KEY (id),
    CONSTRAINT segurancaapi_usuario_fkey FOREIGN KEY (pessoa_id) REFERENCES pessoa(id)
) ENGINE = InnoDB;

-- -----------------------------------------------------
-- Table `reprografia`.`disciplina`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `reprografia`.`disciplina` ;

CREATE TABLE IF NOT EXISTS `reprografia`.`disciplina` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `descricao` VARCHAR(45) NOT NULL,
  `serie` VARCHAR(45) NULL,
  `segmento` VARCHAR(45) NULL,
  `ativo` TINYINT(1) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `reprografia`.`centro_custo`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `reprografia`.`centro_custo` ;

CREATE TABLE IF NOT EXISTS `reprografia`.`centro_custo` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `cota_preta` INT NULL,
  `custo_fixo_preta` DECIMAL(19,4) NULL,
  `custo_fixo_colorida` DECIMAL(19,4) NULL,
  `valor_exc_preta` DECIMAL(19,4) NULL,
  `valor_exc_colorida` DECIMAL(19,4) NULL,
  `data_inicio` DATE NULL,
  `data_fim` DATE NULL,
  `total_preto_impresso` INT NULL DEFAULT 0,
  `total_colorido_impresso` INT NULL DEFAULT 0,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `reprografia`.`professor_disciplina`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `reprografia`.`professor_disciplina` ;

CREATE TABLE IF NOT EXISTS `reprografia`.`professor_disciplina` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `disciplina_id` INT NOT NULL,
  `professor_id` INT NOT NULL,
  CONSTRAINT id_pkey PRIMARY KEY (`id`),
  CONSTRAINT `fk_relacionamento_disciplina`
    FOREIGN KEY (`disciplina_id`)
    REFERENCES `reprografia`.`disciplina` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_relacionamento_professor`
    FOREIGN KEY (`professor_id`)
    REFERENCES `reprografia`.`pessoa` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_relacionamento_disciplina_idx` ON `reprografia`.`professor_disciplina` (`disciplina_id` ASC);

CREATE INDEX `fk_relacionamento_professor_idx` ON `reprografia`.`professor_disciplina` (`professor_id` ASC);


-- -----------------------------------------------------
-- Table `reprografia`.`requisicao`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `reprografia`.`requisicao` ;

CREATE TABLE IF NOT EXISTS `reprografia`.`requisicao` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `duplex` TINYINT(1) NULL,
  `grampeada` TINYINT(1) NULL,
  `colorida` TINYINT(1) NULL,
  `numero_de_paginas` INT NULL,
  `numero_de_copias` INT NULL,
  `custo_da_requisicao` DECIMAL(19,4) NULL,
  `arquivo` TEXT NULL,
  `tamanho_arquivo` INT NULL,
  `data_abertura` DATE NOT NULL,
  `professor_disciplina_id` INT NOT NULL,
  `custo_id` INT NULL,
  `data_conclusao` DATE NULL,
  PRIMARY KEY (`id`),
  CONSTRAINT `fk_requisicao_relacionamento`
    FOREIGN KEY (`professor_disciplina_id`)
    REFERENCES `reprografia`.`professor_disciplina` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_requisicao_custo`
    FOREIGN KEY (`custo_id`)
    REFERENCES `reprografia`.`centro_custo` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_requisicao_relacionamento_idx` ON `reprografia`.`requisicao` (`professor_disciplina_id` ASC);

CREATE INDEX `fk_requisicao_custo_idx` ON `reprografia`.`requisicao` (`custo_id` ASC);


-- -----------------------------------------------------
-- Table `reprografia`.`status`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `reprografia`.`status` ;

CREATE TABLE IF NOT EXISTS `reprografia`.`status` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `descricao` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `reprografia`.`andamento`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `reprografia`.`andamento` ;

CREATE TABLE IF NOT EXISTS `reprografia`.`andamento` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `data` DATE NOT NULL,
  `observacao` TEXT NULL,
  `requisicao_id` INT NOT NULL,
  `status_id` INT NOT NULL,
  `pessoa_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  CONSTRAINT `fk_andamento_requisicao1`
    FOREIGN KEY (`requisicao_id`)
    REFERENCES `reprografia`.`requisicao` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_andamento_status`
    FOREIGN KEY (`status_id`)
    REFERENCES `reprografia`.`status` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_andamento_pessoa`
    FOREIGN KEY (`pessoa_id`)
    REFERENCES `reprografia`.`pessoa` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_andamento_requisicao1_idx` ON `reprografia`.`andamento` (`requisicao_id` ASC);

CREATE INDEX `fk_andamento_status_idx` ON `reprografia`.`andamento` (`status_id` ASC);

CREATE INDEX `fk_andamento_pessoa_idx` ON `reprografia`.`andamento` (`pessoa_id` ASC);


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;

